site_name: Conductor
theme_dir: docs/theme
repo_url: https://github.com/Netflix/conductor
strict: True
pages:
- Introduction: index.md
- 'Getting Started': intro/index.md
- 'Basic Concepts': intro/concepts.md
- 'Highlevel Steps': intro/steps.md
- 'Defining Workflow Metadata':
   - 'Definitions': metadata/index.md
   - 'Workflow Tasks': metadata/task.md
   - 'Wiring inputs': metadata/io.md
   - 'System Tasks': metadata/systask.md
   - 'Extended Tasks & Features': extend/tasks.md
- 'Workflow Management': runtime/index.md
- 'Extending Features': extend/index.md
- 'Workflow Metrics':
   - 'Server Metrics': metrics/index.md
   - 'Worker Metrics': metrics/client.md
- License: 'license.md'
theme: readthedocs
markdown_extensions:
- admonition
- toc:
    permalink: True
