# Docker compose for netflix conductor + elasticsearch
version: '2'
services:
  conductor:
    image: conductor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 3000:3000
    depends_on:
      - elasticsearch
      - dynomite
  dynomite:
    image: ipapapa/dynomitedocker
    ports:
      - 8102:8102
      - 22122:22122
  elasticsearch:
    image: elasticsearch
    ports:
      - 9300:9300
