# Docker compose for netflix conductor + elasticsearch + dynomite
version: '2'
services:
  conductor-server:
    image: conductor:server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
      - dynomite
    networks:
      conductornet:
        aliases:
          - conductor-server

  conductor-ui:
    image: conductor:ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - conductor-server
    networks:
      conductornet:
        aliases:
          - conductor-ui

  dynomite:
    image: v1r3n/dynomite
    ports:
      - 8102:8102
      - 22122:22122
      - 22222:22222
    networks:
      conductornet:
        aliases:
          - dyno1

  elasticsearch:
    image: elasticsearch
    ports:
      - 9300:9300
      - 9200:9200
    networks:
      conductornet:
        aliases:
          - es

networks:
  conductornet:
    driver: bridge
